name: "Build & Test"

on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev libgmock-dev

    - name: build main
      run: make
    
    - name: build tests
      run: make test
    
  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: build main
      run: make

    - name: run main
      run: ./main
    
    - name: build tests
      run: make test
    
    - name: run tests
      run: ./test

